variables:
  project: '**/Arbus.Network.csproj'
  testProject: 'Arbus.Network.UnitTests.csproj'
  nugetFeed: 'NuGet.org'
  buildConfiguration: 'Release'

stages:
  - stage: build
    displayName: Build
    pool:
      vmImage: 'Windows-latest'
    jobs:
      - job: build_job
        displayName: Build
        workspace:
          clean: outputs
        steps:
        - checkout: self
          fetchDepth: 1
        - task: Assembly-Info-NetCore@3
          displayName: Set assembly info
          condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))
          inputs:
            Path: '$(Build.SourcesDirectory)'
            FileNames: '$(project)'
            InsertAttributes: true
            FileEncoding: 'auto'
            WriteBOM: false
            VersionNumber: '$(Build.SourceBranchName)'
            PackageVersion: '$(Build.SourceBranchName)'
            LogLevel: 'verbose'
            FailOnWarning: false
            DisableTelemetry: false
        - task: DotNetCoreCLI@2
          displayName: 'Build $(project)'
          inputs:
            command: build
            projects: $(project)
            arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Binaries'
            outputDir: ''
        - task: DotNetCoreCLI@2
          displayName: 'Run $(testProject)'
          inputs:
            command: test
            projects: '**/$(testProject)'
            arguments: '-c Release -s src/tests.runsettings'
            testRunTitle: '$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Build.BuildNumber)'
        - publish: $(Build.ArtifactStagingDirectory)
          displayName: 'Publish $(artifact)'

  - stage: deploy
    displayName: Deploy
    condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))
    pool: 
      vmImage: 'Windows-latest'
    jobs:
      - job: pack
        displayName: Pack binaries
        workspace:
          clean: all
        steps:
          - checkout: self
            fetchDepth: 1
          - download: current
          - task: DotNetCoreCLI@2
            displayName: 'Pack $(project)'
            inputs:
              command: pack
              searchPatternPack: $(project)
              configuration: $(buildConfiguration)
              nobuild: true
              versioningScheme: byEnvVar
              versionEnvVar: Build.SourceBranchName
          - task: NuGetCommand@2
            displayName: 'Push to $(nugetFeed)'
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: '$(nugetFeed)'
