variables:
  project: '**/Arbus.Network.csproj'
  testProject: 'Arbus.Network.UnitTests.csproj'
  nugetFeed: 'NuGet.org'
  buildConfiguration: 'Release'

stages:
  - stage: tests
    displayName: Tests
    pool:
      vmImage: 'Windows-latest'
    jobs:
      - job: test_job
        displayName: Tests
        steps:
        - checkout: self
          fetchDepth: 1
        - task: DotNetCoreCLI@2
          displayName: 'Run UnitTests'
          inputs:
            command: test
            projects: '**/$(testProject)'
            arguments: '-c $(buildConfiguration) -s src/tests.runsettings'
            testRunTitle: '$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Build.BuildNumber)'

  - stage: deploy
    displayName: Deploy
    dependsOn: tests
    condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))
    pool: 
      vmImage: 'Windows-latest'
    jobs:
      - job: pack
        displayName: Pack NuGet
        workspace:
          clean: all
        steps:
          - checkout: self
            fetchDepth: 1
          - task: Assembly-Info-NetCore@3
            displayName: Set assembly info
            inputs:
              Path: '$(Build.SourcesDirectory)'
              FileNames: '$(project)'
              InsertAttributes: true
              FileEncoding: 'auto'
              WriteBOM: false
              VersionNumber: '$(Build.SourceBranchName)'
              PackageVersion: '$(Build.SourceBranchName)'
              LogLevel: 'verbose'
              FailOnWarning: false
              DisableTelemetry: false
          - task: DotNetCoreCLI@2
            displayName: 'Pack $(project)'
            inputs:
              command: pack
              searchPatternPack: $(project)
              configuration: $(buildConfiguration)
              versioningScheme: byEnvVar
              versionEnvVar: Build.SourceBranchName
          - task: NuGetCommand@2
            displayName: 'Push to $(nugetFeed)'
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: '$(nugetFeed)'
