variables:
  project: 'Arbus.Network.csproj'
  testProject: 'Arbus.Network.UnitTests.csproj'
  artifact: 'ArbusNetwork.Artifact'

stages:
  - stage: build
    displayName: Build
    pool:
      name: 'Building pool'
      demands:
        - agent.os -equals Windows_NT
    jobs:
      - job: build_job
        displayName: Build
        workspace:
          clean: outputs
        steps:
        - checkout: self
          fetchDepth: 1
        - task: DotNetCoreCLI@2
          displayName: 'Build $(project)'
          inputs:
            command: build
            projects: '**/$(project)'
            outputDir: '$(Build.ArtifactStagingDirectory)/Build'
        - task: DotNetCoreCLI@2
          displayName: 'Run $(testProject)'
          inputs:
            command: test
            projects: '**/$(testProject)'
            arguments: '-s src/tests.runsettings'
            configuration: 'Release'
            testRunTitle: '$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Build.BuildNumber)'
        - publish: $(Build.ArtifactStagingDirectory)
          displayName: 'Publish $(artifact)'
          artifact: $(artifact)